[package]
name = "rusty_krab"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.27" }
egui_extras = { version = "0.27" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
directories = "5"
anyhow = "1"
